repos:
  - repo: local
    hooks:
      - id: pep8
        name: check formatting
        entry: autopep8 --recursive --ignore=E501,W504 --exclude="*Colonel*" --exit-code --in-place topfarm
        language: system
        pass_filenames: false
        stages: [pre-commit]
