# ==================================================================
# Creating a simple docker image for TOPFARM testing and docs
# ==================================================================
FROM continuumio/anaconda3:latest
MAINTAINER Jenni Rinker <rink@dtu.dk>


# get list of update linux files and install lib for matplotlib
#   (anaconda3:5.0.0 image doesn't have the library)
#    also install "make" because image doesn't have it either
#   also install gcc and gfortran for fused-wake/wind-io
RUN apt-get update && \
    apt-get install make && \
    apt-get install libgl1-mesa-glx -y && \
    apt-get install gcc gfortran -y


# use conda to update itself and install packages not in the
#   anaconda3 image
RUN conda update -y conda && \
    conda install -y sphinx_rtd_theme && \
    conda install -y pytest-cov && \
	conda install -y mock && \
    conda clean -y --all
	
# install mpi functionality. Note that you might need to increase the memory limit (from the factory default setting) for the docker engine to be able to install these packages.
RUN conda install -c conda-forge openmpi
RUN conda install -c conda-forge petsc4py 
#RUN conda install -c anaconda mpi4py
RUN conda install -c conda-forge mpi4py

# update pip then install openmdao, windio and fused-wake (nocache to save space)
RUN pip install --upgrade pip && \
    pip install --no-cache-dir openmdao==2.6 && \
    pip install --no-cache-dir git+https://github.com/FUSED-Wind/windIO.git && \
    pip install --no-cache-dir git+https://gitlab.windenergy.dtu.dk/TOPFARM/FUSED-Wake.git

RUN pip install --upgrade git+git://github.com/FUSED-Wind/FUSED-Wake@master && \
	pip install --upgrade git+https://gitlab.windenergy.dtu.dk/TOPFARM/PyWake.git && \
	pip install --upgrade git+https://github.com/WISDEM/akima.git

RUN	git clone https://gitlab.windenergy.dtu.dk/TOPFARM/FLORISSE.git && \
	cd FLORISSE && \
	git checkout develop-1 && \
	cd src/florisse && \
	gcc -fPIC -c adStack.c  && \
	gfortran -fPIC -c adBuffer.f && \
	f2py -c --opt=-O2 -m _floris floris.f90 adBuffer.o adStack.o && \
	cd .. && \
	cd .. && \
	pip install .

RUN pip install --upgrade git+https://gitlab.windenergy.dtu.dk/TOPFARM/PlantEnergy.git@develop && \
	pip install sphinx --upgrade && \
	pip install nbsphinx==0.3.5 && \
	pip install git+https://github.com/vidartf/nbsphinx-link.git

